name: Check for new files in sge-testnet-1/gentxs directory

on:
  push:
    # We want to trigger this workflow when a file is pushed to sge-testnet-1/gentxs directory
    # paths:
    #  - 'sge-testnet-1/gentxs/**'
  pull_request:
    # We also want to trigger this workflow when a pull request is opened with changes to the sge-testnet-1/gentxs directory
    paths:
      - 'sge-testnet-1/gentxs/**'

env:
  MIN_STAKE: 50000

jobs:
  check-gentxs-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check gentxs directory
        run: |
          for file in sge-testnet-1/gentxs/*.json; do
            NAME=$(echo $file | cut -f 1 -d '.')
            STAKED=$(jq -r '.body.messages[0].value.amount' "$file")
            if [[ $STAKED -ge $MIN_STAKE ]]; then
              # If the validator meets the criteria, print a message
              echo "$NAME has $STAKED tokens staked"
            else
              # If the validator does not meet the criteria, exit with an error code
              echo "$NAME has less than $MIN_STAKE tokens staked"
              exit 1
            fi
          done

