name: Check for new files in sge-testnet-1/gentxs directory

on:
  push:
    # We want to trigger this workflow when a file is pushed to sge-testnet-1/gentxs directory
    paths:
      - 'sge-testnet-1/gentxs/**'
  pull_request:
    # We also want to trigger this workflow when a pull request is opened with changes to the sge-testnet-1/gentxs directory
    paths:
      - 'sge-testnet-1/gentxs/**'

jobs:
  check-gentxs-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check gentx amount
        # We want to check the gentx amount only when a new file is added
        if: github.event_name == 'push'
        # We need to set the GITHUB_TOKEN environment variable to be able to use the GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # We get the commit hash of the latest commit
          commit=$(jq -r '.head_commit.id' $GITHUB_EVENT_PATH)
          # We get the list of files that were added in the latest commit
          files=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$commit" \
            | jq -r '.files[].filename' \
            | grep -E '^sge-testnet-1/gentxs/')
          # We check if there are new files added to the gentxs directory
          if [ -n "$files" ]; then
            # If there are new files, we check the gentx amount
            amount=$(jq -r '.body.messages[0].value.amount' $(echo "$files" | xargs cat))
            if [ "$amount" -ge 10000 ]; then
              echo "Gentx approved"
            else
              echo "Gentx amount too low"
              exit 1
            fi
          else
            # If there are no new files, we skip the check
            echo "No new gentx files found"
          fi
        shell: bash
