name: Check for new files in sge-testnet-1/gentxs directory

on:
  push:
    paths:
      - 'sge-testnet-1/gentxs/**'
  pull_request:
    paths:
      - 'sge-testnet-1/gentxs/**'

jobs:
  check-gentxs-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Check gentx amount
        if: env.FILES_ADDED == 'true'
        run: |
          amount=$(jq -r '.body.messages[0].value.amount' $GITHUB_EVENT_PATH)
          if [ "$amount" -ge 10000 ]; then
            echo "Gentx approved"
          else
            echo "Gentx amount too low"
            exit 1
          fi
        shell: bash
